name: yeedart
description: Simple Dart library that lets you control Yeelight devices over LAN.
version: 0.3.2
homepage: https://github.com/janstol/yeedart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  meta: ^1.8.0

dev_dependencies:
  lint: ^1.10.0
  mockito: ^5.3.2
  path: ^1.8.2
  test: ^1.21.6
